---
- name: Network | Install nftables
  ansible.builtin.apt:
    name: nftables

- name: Network | Create /etc/nftables.d folder
  ansible.builtin.file:
    path: /etc/nftables.d
    state: directory
    mode: "0755"

- name: Network | Copy nftables.conf
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0755"
    validate: nft -c -f %s
  notify: apply fw
