---
- name: Config | Restart resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  listen: restart systemd

- name: Config | Restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  listen: restart systemd
