---
- name: Prepare test environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure dependencies are installed
      ansible.builtin.apt:
        update_cache: true
        name:
          - sudo
          - python3
          - gnupg
