---
- name: Network | Apply nftables config
  ansible.builtin.systemd_service:
    name: nftables
    state: reloaded
  listen: apply nft

- name: Network | Start nftables service
  ansible.builtin.systemd_service:
    name: nftables
    state: started
    enabled: true
  listen: apply nft

- name: Network | Reload SSH
  ansible.builtin.systemd_service:
    name: ssh
    state: reloaded
  listen:
    - reload ssh
    - restart ssh
