---
dependency:
  name: galaxy

driver:
  name: ${DRIVER:-podman}

platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    command: ${MOLECULE_CONTAINER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  options:
    D: true
  config_options:
    defaults:
      callbacks_enabled: timer

verifier:
  name: ansible
  options:
    D: true
