---
dependency:
  name: galaxy

driver:
  name: ${DRIVER:-docker}

platforms:
  - name: instance
    image: docker.io/ubuntu:24.04
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  options:
    D: true
  config_options:
    defaults:
      callbacks_enabled: timer

verifier:
  name: ansible
  options:
    D: true
