---
users_default_user: root
users_default_user_pubkeys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBXxonWeQySogM1D61oHzBM1JR7KZekotRmOGdpo5XS test@localhost

users_groups:
  - name: sshsystemgroup
    system: true
  - name: notasystemgroup

users_users:
  - username: testuser
    full_name: Test User
    groups:
      - sudo
    ssh_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFBXxonWeQySogM1D61oHzBM1JR7KZekotRmOGdpo5XS test@localhost

  - username: testsysuser
    full_name: Test System User
    system: true