---
- name: Users config
  tags: users
  block:

  - name: Users | Validate users input
    ansible.builtin.assert:
      that: not (users_users and users_git_users.git_url is defined)
      msg: users_users and users_git_users are mutually exclusive.

  - name: Users | Add pubkey to authorized_keys for {{ users_default_user }}
    ansible.posix.authorized_key:
      user: "{{ users_default_user }}"
      key: "{{ users_default_user_pubkeys }}"
      exclusive: true
    when: users_default_user_pubkeys

  - name: Users | Create groups
    ansible.builtin.group:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
      system: "{{ item.system | default(false) }}"
    loop: "{{ users_groups }}"

  - name: Users | Get users from git
    when: users_git_users.git_url is defined
    block:

    - name: Users | Create a temporary directory
      ansible.builtin.file:
        path: "{{ _users_git_path }}"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Users | Clone git repository
      ansible.builtin.git:
        accept_newhostkey: "{{ users_git_users.accept_newhostkey | default(false) }}"
        repo: "{{ users_git_users.git_url }}"
        dest: "{{ _users_git_path }}"
        version: "{{ users_git_users.git_version | default('HEAD') }}"
        single_branch: true
        force: true

    - name: Users | Slurp user data from cloned repository
      ansible.builtin.slurp:
        src: "{{ _users_git_path }}/users.yml"
      register: _slurped_users

    - name: Users | Decode and set user data
      ansible.builtin.set_fact:
        _loaded_users: "{{ _slurped_users.content | b64decode | from_yaml }}"


  - name: Users | Set user data
    ansible.builtin.set_fact:
      _users_data: "{{ (users_git_users.git_url is defined) | ternary(_loaded_users.users_users, users_users) }}"

  - name: Users | Create the users
    ansible.builtin.user:
      name: "{{ item.username }}"
      comment: "{{ item.full_name }}"
      password: "{{ item.password | default('*') }}"
      shell: "{{ item.shell | default(users_system_default_shell if item.system | default(false) else users_default_shell) }}"
      groups: "{{ item.groups | default([]) }}"
      append: false
      state: "{{ item.state | default('present') }}"
      system: "{{ item.system | default(false) }}"
      remove: "{{ item.remove | default(true) }}"
    loop: "{{ _users_data }}"

  - name: Users | Add pubkey to authorized_keys
    ansible.posix.authorized_key:
      user: "{{ item.username }}"
      key: "{{ item.ssh_keys }}"
      exclusive: true
    loop: "{{ _users_data }}"
    ignore_errors: "{{ ansible_check_mode }}"
    when: not (item.system | default(false))

  # Lingering is a systemd feature that keeps a user's session running even after they log out
  # This is useful for services that need to run as a user, like a container run with podman
  - name: Users | Enable linger for user {{ item.username }}
    ansible.builtin.file:
      dest: /var/lib/systemd/linger/{{ item.username }}
      mode: "0644"
      state: touch
      modification_time: preserve
      access_time: preserve
    loop: "{{ _users_data }}"
    when: item.get('options', {}).linger | default(false)

  - name: Users | Allow nopasswd sudo
    community.general.sudoers:
      name: custom_sudo
      group: "{{ _users_sudo_group_name }}"
      commands: ALL
      validation: required
    when: users_nopasswd_sudo
