---
- name: Users config
  tags: users
  block:

  - name: Users | Add pubkey to authorized_keys for {{ users_default_user }}
    ansible.posix.authorized_key:
      user: "{{ users_default_user }}"
      key: "{{ users_default_user_pubkeys }}"
      exclusive: true
    when: users_default_user_pubkeys

  - name: Users | Create groups
    ansible.builtin.group:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
      system: "{{ item.system | default(false) }}"
    loop: "{{ users_groups | unique }}"

  - name: Users | Create extra users
    ansible.builtin.user:
      name: "{{ item.username }}"
      comment: "{{ item.full_name }}"
      password: "{{ item.password | default('*') }}"
      shell: "{{ item.shell | default(users_default_shell) }}"
      groups: "{{ item.groups | default([]) }}"
      append: false
      state: "{{ item.state | default('present') }}"
      system: "{{ item.system | default(false) }}"
      remove: "{{ item.remove | default(true) }}"
    loop: "{{ users_users }}"

  - name: Users | Add pubkey to authorized_keys
    ansible.posix.authorized_key:
      user: "{{ item.username }}"
      key: "{{ item.ssh_keys }}"
      exclusive: true
    loop: "{{ users_users }}"
    ignore_errors: "{{ ansible_check_mode }}"
    when: not (item.system | default(false))

  # Lingering is a systemd feature that keeps a user's session running even after they log out
  # This is useful for services that need to run as a user, like a container run with podman
  - name: Users | Enable linger for user {{ item.username }}
    ansible.builtin.file:
      dest: /var/lib/systemd/linger/{{ item.username }}
      mode: "0644"
      state: touch
      modification_time: preserve
      access_time: preserve
    loop: "{{ users_users }}"
    when: item.options.linger is defined and item.options.linger

  - name: Users | Allow nopasswd sudo
    community.general.sudoers:
      name: custom_sudo
      group: sudo
      commands: ALL
      validation: required
    when: users_nopasswd_sudo
