---
- name: Config | Configure system
  tags: config
  block:

  - name: Config | Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"
    when: config_update_hostname

  - name: Config | Put hostname in /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "127.0.0.1 {{ inventory_hostname }}"
      regexp: '^127\.0\.0\.1\s+{{ inventory_hostname }}'
    when: config_update_hostname

  - name: Config | Configure systemd
    ansible.builtin.blockinfile:
      path: "/etc/systemd/{{ item.key }}"
      block: "{{ item.value }}"
    loop: "{{ config_systemd_configurations_blocks | dict2items }}"
    notify: restart systemd

  - name: Config | Apply mountpoints
    ansible.builtin.include_tasks: mount_drives.yml
    loop: "{{ config_mount_points }}"
