---
- name: Prepare test environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure dependencies are installed
      ansible.builtin.apt:
        update_cache: true
        name:
          - sudo
          - python3
          - openssh-server
          - ufw

    - name: Start ufw
      ansible.builtin.systemd:
        name: ufw
        state: started

    - name: Create sshd config dir
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d
        state: directory

    - name: Ensure /run/sshd directory exists
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: '0755'
