---
- name: Verify packages installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
      register: packages

    - name: Assert that packages are installed
      ansible.builtin.assert:
        that:
          - packages.ansible_facts.packages['nftables'] is defined
          - packages.ansible_facts.packages['firewalld'] is defined
          - packages.ansible_facts.packages['ufw'] is not defined

    - name: Check firewall rules
      ansible.builtin.command: nft list ruleset
      register: nft_rules
      failed_when: "'filter_IN_public' not in nft_rules.stdout"

    - name: Check for PasswordAuthentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/custom_sshd.conf
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      check_mode: true
      register: password_auth_check
      failed_when: password_auth_check is changed
