name: Lint Ansible Collection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run YAML and Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install ansible-lint

      - name: Run yamllint
        run: yamllint -c .yamllint node_base

      - name: Run ansible-lint
        run: ansible-lint -c .ansible-lint node_base
