name: check PR (packages)

on:
  pull_request:
    paths:
      - node_base/roles/packages/**
      - .github/workflows/pr-packages.yml
      - .github/workflows/reusable-molecule.yml
      - '!.github/workflows/pri-*.yml'
      - '!.github/workflows/reusablei-*.yml'
      - '!*.md'
  # TODO: remove when enforcing PRs
  push:
    branches:
      - main
    paths:
      - node_base/roles/packages/**
      - .github/workflows/pr-packages.yml
      - .github/workflows/reusable-molecule.yml
      - '!.github/workflows/pri-*.yml'
      - '!.github/workflows/reusablei-*.yml'
      - '!*.md'

jobs:
  run-molecule-tests:
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      collection-name: node_base
      role-name: packages
