name: check PR (users)

on:
  pull_request:
    paths:
      - node_base/roles/users/**
      - .github/**
  # TODO: remove when enforcing PRs
  push:
    branches:
      - main
    paths:
      - node_base/roles/users/**
      - .github/**

env:
  USERS_REPO_KEYFILE: ${{ secrets.USERS_REPO_KEYFILE }}

jobs:
  run-molecule-tests:
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      collection-name: node_base
      role-name: users
