name: check PR (users)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - node_base/roles/users/**
      - .github/**

jobs:
  run-molecule-tests:
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      collection-name: node_base
      role-name: users