name: check PR (users)

on:
  pull_request:
    paths:
      - node_base/roles/users/**
      - .github/workflows/pr-users.yml
      - .github/workflows/reusable-molecule.yml
      - '!.github/workflows/pri-*.yml'
      - '!.github/workflows/reusablei-*.yml'
      - '!**.md'
  # TODO: remove when enforcing PRs
  push:
    branches:
      - main
    paths:
      - node_base/roles/users/**
      - .github/workflows/pr-users.yml
      - .github/workflows/reusable-molecule.yml
      - '!.github/workflows/pri-*.yml'
      - '!.github/workflows/reusablei-*.yml'
      - '!**.md'

jobs:
  run-molecule-tests:
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      collection-name: node_base
      role-name: users
    secrets:
      USERS_REPO_PAT: ${{ secrets.USERS_REPO_PAT }}
