on:
  workflow_call:
    inputs:
      collection-name:
        required: true
        type: string
      role-name:
        required: true
        type: string
jobs:
  molecule:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if there are molecule tests
        run: |
          if [ -d "molecule" ]; then
            echo "MOLECULE_TESTS=YES" >> "${GITHUB_ENV}"
          fi
        working-directory: ${{ inputs.collection-name }}/roles/${{ inputs.role-name }}
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25
        with:
          args: "-c ../../"
          setup_python: "false"
          working_directory: ${{ inputs.collection-name }}/roles/${{ inputs.role-name }}
          requirements_file: ../../requirements.yml
      - name: Set up molecule
        if: env.MOLECULE_TESTS == 'YES'
        run: pip install --no-cache-dir molecule molecule-plugins[podman]
      - name: Run molecule tests
        if: env.MOLECULE_TESTS == 'YES'
        run: molecule test --all
        working-directory: ${{ inputs.collection-name }}/roles/${{ inputs.role-name }}
